name: Laravel

on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'

    - name: Install Dependencies
      run: |
        composer install --no-scripts --no-progress --prefer-dist

    - name: Prepare Laravel ENV
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Run Laravel Tests
      run: php artisan test
